image: alpine/latest
packages:
  - opam
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~johnridesabike/acutis
secrets:
  - c646f54e-8b1c-45e7-ba55-d51b2e27761a
tasks:
  - install: |
      cd acutis
      opam init --auto-setup --bare
      opam switch create . --deps-only --with-test --with-doc --yes
  - build_and_test: |
      cd acutis
      opam exec -- dune build @ci --profile release
  - deploy_docs: |
      set +x
      . ~/.netlify_auth
      set -x
      cd acutis/docs
      npm ci
      npm run deploy
