#!/usr/bin/env node

/**
 *    Copyright 2021 John Jackson
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

const util = require("util");
const fs = require("fs");
const minimist = require("minimist");
const Acutis = require("./dist/acutis");
const { loadTemplate, filenameToComponent } = require("./node-utils");
const { version } = require("./package.json");
const { stdin } = process;

const readFile = util.promisify(fs.readFile);
const writeFile = util.promisify(fs.writeFile);

function getStdin() {
  return new Promise((resolve, reject) => {
    let result = "";
    if (stdin.isTTY) {
      return resolve(result);
    }
    stdin.setEncoding("utf8");
    stdin.on("readable", () => {
      let chunk;
      while (null !== (chunk = stdin.read())) {
        result += chunk;
      }
    });
    stdin.on("end", () => resolve(result));
    stdin.on("error", reject);
  });
}

const args = minimist(process.argv.slice(2), {
  string: ["data", "output"],
  boolean: ["async", "help", "table", "version"],
  alias: {
    a: "async",
    d: "data",
    h: "help",
    o: "output",
    t: "table",
    v: "version",
  },
});

if (args.version) {
  console.log(version);
} else if (args.help || args._.length === 0) {
  console.log(`Usage:
  acutis [options] [template] [templates...]

Options:
  -a, --async                   Enable asynchronous templates. Default: false.
  -d, --data                    The path to the JSON data file. Default: stdin.
  -o, --output                  The path to write the output. Default: stdout.
  -t, --table                   Print errors in a table. Default: false.
  -h, --help                    Show this message and exit.
  -v, --version                 Show the version and exit.

Templates:
  The first template listed is the root template. Templates with .js or .mjs
  extensions are rendered using their default export function. For all other
  file types, their text content is used as the template.

Examples:
  acutis --data=data.json --output=index.html Index.acutis Header.js Footer.acutis
  acutis Index.acutis _includes/**/*.(js|mjs|acutis) < data.json > index.html
  curl https://example.com/api | acutis Index.acutis *.(js|acutis) -o index.html 
`);
} else {
  Promise.all(
    args._.map((fileName) =>
      loadTemplate(fileName).then((file) => ({
        name: filenameToComponent(fileName),
        content: file,
      }))
    )
  )
    .then((files) => {
      const props = (args.data ? readFile(args.data) : getStdin()).then(
        (contents) => {
          if (contents === "") {
            return {};
          } else {
            return JSON.parse(contents);
          }
        }
      );
      if (!files[0] || !files[0].content) {
        throw Error("I couldn't load the main template.");
      }
      const MainTemplate = files[0].content;
      const templates = {};
      for (file of files) {
        templates[file.name] = file.content;
      }
      const render = args.async
        ? Acutis.Environment.Async.make(templates)
        : Acutis.Environment.make(templates);
      return props
        .then((props) => MainTemplate(render, props, {}))
        .then(({ NAME, VAL }) => {
          if (NAME === "errors") {
            if (args.table) {
              console.table(VAL);
            } else {
              console.error(VAL);
            }
            throw new Error("I can't continue due to these errors.");
          } else {
            return VAL;
          }
        });
    })
    .then((result) => {
      if (args.output) {
        return writeFile(args.output, result).then(() =>
          console.log(`I successfully wrote ${args.output}.`)
        );
      } else {
        return process.stdout.write(result, "utf8");
      }
    })
    .catch((e) => {
      if (e.message) {
        console.error(e.message);
      } else {
        console.error(e);
      }
      process.exitCode = 1;
    });
}
