// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "@rescript/std/lib/es6/curry.js";

function src(name, src$1) {
  return {
          TAG: /* Acutis */0,
          _0: name,
          _1: src$1
        };
}

function fnU(name, props, children, f) {
  return {
          TAG: /* Function */1,
          _0: name,
          _1: props,
          _2: children,
          _3: f
        };
}

function fn(name, props, children, f) {
  return {
          TAG: /* Function */1,
          _0: name,
          _1: props,
          _2: children,
          _3: Curry.__3(f)
        };
}

export {
  src ,
  fnU ,
  fn ,
  
}
/* No side effect */
