  $ acutis \
  >   --mode js \
  >   template.acutis \
  >   --fun ./jsfile.cjs externalFunction "children = string"
  /* THIS FILE WAS GENERATED BY ACUTIS. */
  
  import * as External_jsfile from "./jsfile.cjs";
  
  async function pattern_failure_error() {
    throw new Error("This pattern-matching failed to find a path.\n\
  This probably means there's a problem with the compiler.");
  }
  
  async function decode_error(arg0, arg1, debug_stack) {
    throw new Error([
      "Decode error.\n\
  Expected type:\n\
    ",
      arg0,
      "\n\
  Recieved value:\n\
    ",
      arg1,
      "\n\
  In field: ",
      debug_stack.join(" -> "),
    ].join(""));
  }
  
  let escapes = {
    "&": "&amp;",
    '"': "&quot;",
    "'": "&apos;",
    ">": "&gt;",
    "<": "&lt;",
    "/": "&#x2F;",
    "`": "&#x60;",
    "=": "&#x3D;",
  };
  
  function acutis_escape(str) {
    let result = "";
    for (let c of str) {
      result += escapes[c] || c;
    }
    return result;
  }
  
  async function template_ExternalFunction(input1) {
    let data = new Object();
    let input2 = input1.get("children");
    data.children = input2;
    return External_jsfile.externalFunction(data);
  }
  
  export default async function main(input1) {
    let data = new Map();
    let debug_stack = new Array();
    return (await Promise.all([
      (async function () {
        let resolved0 = (await Promise.all([" text "])).join("");
        let arg0 = new Map([["children", resolved0]]);
        return template_ExternalFunction(arg0);
      })(),
      "\n\
  ",
    ])).join("");
  }
  

  $ acutis \
  >   --mode cjs \
  >   template.acutis \
  >   --fun ./jsfile.cjs externalFunction "children = string"
  /* THIS FILE WAS GENERATED BY ACUTIS. */
  
  const External_jsfile = require("./jsfile.cjs");
  
  async function pattern_failure_error() {
    throw new Error("This pattern-matching failed to find a path.\n\
  This probably means there's a problem with the compiler.");
  }
  
  async function decode_error(arg0, arg1, debug_stack) {
    throw new Error([
      "Decode error.\n\
  Expected type:\n\
    ",
      arg0,
      "\n\
  Recieved value:\n\
    ",
      arg1,
      "\n\
  In field: ",
      debug_stack.join(" -> "),
    ].join(""));
  }
  
  let escapes = {
    "&": "&amp;",
    '"': "&quot;",
    "'": "&apos;",
    ">": "&gt;",
    "<": "&lt;",
    "/": "&#x2F;",
    "`": "&#x60;",
    "=": "&#x3D;",
  };
  
  function acutis_escape(str) {
    let result = "";
    for (let c of str) {
      result += escapes[c] || c;
    }
    return result;
  }
  
  async function template_ExternalFunction(input1) {
    let data = new Object();
    let input2 = input1.get("children");
    data.children = input2;
    return External_jsfile.externalFunction(data);
  }
  
  module.exports = async function main(input1) {
    let data = new Map();
    let debug_stack = new Array();
    return (await Promise.all([
      (async function () {
        let resolved0 = (await Promise.all([" text "])).join("");
        let arg0 = new Map([["children", resolved0]]);
        return template_ExternalFunction(arg0);
      })(),
      "\n\
  ",
    ])).join("");
  }
  
