(**************************************************************************)
(*                                                                        *)
(*                   Copyright (c) 2022 John Jackson.                     *)
(*                                                                        *)
(*  This Source Code Form is subject to the terms of the Mozilla Public   *)
(*  License, v. 2.0. If a copy of the MPL was not distributed with this   *)
(*  file, You can obtain one at http://mozilla.org/MPL/2.0/.              *)
(*                                                                        *)
(**************************************************************************)

(** The lexer module generated by [ocamllex]. *)

type state
(** This The lexer relies on different rules depending on the type of expression
    it's currently in (echo, text, etc). This state type tracks that in addition
    to the regular [lexbuf] state. *)

val make_state : Lexing.lexbuf -> state
val make_state_interface : Lexing.lexbuf -> state
val loc : state -> Lexing.position * Lexing.position
val supplier : state -> unit -> Parser.token * Lexing.position * Lexing.position
