(**************************************************************************)
(*                                                                        *)
(*                   Copyright (c) 2022 John Jackson.                     *)
(*                                                                        *)
(*  This Source Code Form is subject to the terms of the Mozilla Public   *)
(*  License, v. 2.0. If a copy of the MPL was not distributed with this   *)
(*  file, You can obtain one at http://mozilla.org/MPL/2.0/.              *)
(*                                                                        *)
(**************************************************************************)

(** The lexer module generated by [ocamllex]. *)

val acutis : Lexing.lexbuf -> Parser.MenhirInterpreter.supplier
val interface : Lexing.lexbuf -> Parser.MenhirInterpreter.supplier
