(**************************************************************************)
(*                                                                        *)
(*                   Copyright (c) 2022 John Jackson.                     *)
(*                                                                        *)
(*  This Source Code Form is subject to the terms of the Mozilla Public   *)
(*  License, v. 2.0. If a copy of the MPL was not distributed with this   *)
(*  file, You can obtain one at http://mozilla.org/MPL/2.0/.              *)
(*                                                                        *)
(**************************************************************************)

(** The lexer module generated by [ocamllex]. *)

type state
(** The lexer relies on different rules depending on the type of expression
    it's currently in (echo, text, etc). This state type tracks that as an
    addition to the regular [lexbuf] state. *)

val make_state : unit -> state
val make_state_interface : unit -> state
val acutis : state -> Lexing.lexbuf -> Parser.token
