// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Render$AcutisLang = require("./Render.js");
var Result$AcutisLang = require("./Result.js");
var Source$AcutisLang = require("./Source.js");
var Compile$AcutisLang = require("./Compile.js");
var Typescheme$AcutisLang = require("./Typescheme.js");

var Compile = Compile$AcutisLang;

var Render = Render$AcutisLang;

var Result = Result$AcutisLang;

var Source = Source$AcutisLang;

var Typescheme = Typescheme$AcutisLang;

exports.Compile = Compile;
exports.Render = Render;
exports.Result = Result;
exports.Source = Source;
exports.Typescheme = Typescheme;
/* Render-AcutisLang Not a pure module */
