// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("@rescript/std/lib/js/curry.js");

function src(name, src$1) {
  return {
          TAG: /* Acutis */0,
          _0: name,
          _1: src$1
        };
}

function fnU(name, props, children, f) {
  return {
          TAG: /* Function */1,
          _0: name,
          _1: props,
          _2: children,
          _3: f
        };
}

function fn(name, props, children, f) {
  return {
          TAG: /* Function */1,
          _0: name,
          _1: props,
          _2: children,
          _3: Curry.__3(f)
        };
}

exports.src = src;
exports.fnU = fnU;
exports.fn = fn;
/* No side effect */
